"""remove_preco_plano_modalidade

Revision ID: 0b46492a7eba
Revises: 2eff77fe9dc7
Create Date: 2026-09-01 16:51:01.059763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0b46492a7eba'
down_revision: Union[str, None] = '2eff77fe9dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modalidades', 'preco_plano')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalidades', sa.Column('preco_plano', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    # ### end Alembic commands ###
