"""configuracao_plataforma

Revision ID: 27e2c21cf2f0
Revises: 5e150c836791
Create Date: 2026-08-20 00:25:18.468599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27e2c21cf2f0'
down_revision: Union[str, None] = '5e150c836791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_plataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxa_servico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_plataforma')
    # ### end Alembic commands ###
