"""redefinicao_senha

Revision ID: 2eff77fe9dc7
Revises: 8135db14a42b
Create Date: 2026-09-01 14:00:59.442564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2eff77fe9dc7'
down_revision: Union[str, None] = '8135db14a42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redefinicoes_senha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redefinicoes_senha_token'), 'redefinicoes_senha', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redefinicoes_senha_token'), table_name='redefinicoes_senha')
    op.drop_table('redefinicoes_senha')
    # ### end Alembic commands ###
