"""turma_excecoes

Revision ID: 3576534cddbc
Revises: bb570b64f90a
Create Date: 2026-08-20 14:17:59.894581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3576534cddbc'
down_revision: Union[str, None] = 'bb570b64f90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_excecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma_id', 'data', name='uq_turma_excecao_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_excecoes')
    # ### end Alembic commands ###
