"""historico_cancelamentos

Revision ID: 4d52440db29c
Revises: 679e314afdbb
Create Date: 2026-09-01 21:36:42.636379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d52440db29c'
down_revision: Union[str, None] = '679e314afdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assinaturas', sa.Column('cancelado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assinaturas', 'users', ['cancelado_por_id'], ['id'])
    op.add_column('creditos_reposicao', sa.Column('cancelado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'creditos_reposicao', 'users', ['cancelado_por_id'], ['id'])
    op.add_column('matricula_excecoes', sa.Column('cancelado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matricula_excecoes', 'users', ['cancelado_por_id'], ['id'])
    op.add_column('matriculas', sa.Column('cancelado_por_id', sa.Integer(), nullable=True))
    op.add_column('matriculas', sa.Column('cancelado_em', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'matriculas', 'users', ['cancelado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.drop_column('matriculas', 'cancelado_em')
    op.drop_column('matriculas', 'cancelado_por_id')
    op.drop_constraint(None, 'matricula_excecoes', type_='foreignkey')
    op.drop_column('matricula_excecoes', 'cancelado_por_id')
    op.drop_constraint(None, 'creditos_reposicao', type_='foreignkey')
    op.drop_column('creditos_reposicao', 'cancelado_por_id')
    op.drop_constraint(None, 'assinaturas', type_='foreignkey')
    op.drop_column('assinaturas', 'cancelado_por_id')
    # ### end Alembic commands ###
