"""schema inicial

Revision ID: 5e150c836791
Revises: 
Create Date: 2026-08-14 20:46:18.407132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e150c836791'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('contato', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('forma_pagamento_preferida', sa.Enum('PIX', 'DINHEIRO', 'WELLHUB', 'TOTALPASS', name='formapagamento'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('quadras', sa.JSON(), nullable=False),
    sa.Column('formas_pagamento_habilitadas', sa.JSON(), nullable=False),
    sa.Column('prazo_credito_dias', sa.Integer(), nullable=False),
    sa.Column('place_api_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('contato', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('modalidades', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN_POINT', 'PROFESSOR', 'ALUNO', name='role'), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('preco_avulso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_plano', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modelo_repasse', sa.Enum('PERCENTUAL', 'VALOR_FIXO_MENSAL', 'VALOR_FIXO_POR_AULA', name='modelorepasse'), nullable=False),
    sa.Column('valor_repasse', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVO', 'INATIVO', 'RECUSADO', name='vinculostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vinculo_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=60), nullable=False),
    sa.Column('quadra', sa.String(length=60), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.Column('recorrencia', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vinculo_id'], ['vinculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('AVULSA', 'MENSAL', name='matriculatipo'), nullable=False),
    sa.Column('status', sa.Enum('EM_ANALISE', 'ATIVA', 'RECUSADA', 'CANCELADA', name='matriculastatus'), nullable=False),
    sa.Column('fonte_pagamento', sa.Enum('PIX', 'DINHEIRO', name='pagamentomeio'), nullable=False),
    sa.Column('repasse_override_modelo', sa.Enum('PERCENTUAL', 'VALOR_FIXO_MENSAL', 'VALOR_FIXO_POR_AULA', name='modelorepasse'), nullable=True),
    sa.Column('repasse_override_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('origem', sa.Enum('PRESUMIDO', name='checkinorigem'), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADO', 'PENDENTE_ATRIBUICAO', name='checkinstatus'), nullable=False),
    sa.Column('falta_marcada_professor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditos_reposicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('FORCA_MAIOR', 'CANCELAMENTO_ALUNO', name='creditomotivo'), nullable=False),
    sa.Column('data_expiracao', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'USADO', 'EXPIRADO', name='creditostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meio', sa.Enum('PIX', 'DINHEIRO', name='pagamentomeio'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'ESTORNADO', name='pagamentostatus'), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('creditos_reposicao')
    op.drop_table('checkins')
    op.drop_table('matriculas')
    op.drop_table('turmas')
    op.drop_table('vinculos')
    op.drop_table('users')
    op.drop_table('professores')
    op.drop_table('points')
    op.drop_table('alunos')
    # ### end Alembic commands ###
