"""modalidade_quadra_turma

Revision ID: 7d60f766a5ab
Revises: ecb8126b4bb7
Create Date: 2026-08-20 01:41:52.185390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '7d60f766a5ab'
down_revision: Union[str, None] = 'ecb8126b4bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('duracao_padrao_minutos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quadras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modalidade_quadras',
    sa.Column('modalidade_id', sa.Integer(), nullable=False),
    sa.Column('quadra_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidades.id'], ),
    sa.ForeignKeyConstraint(['quadra_id'], ['quadras.id'], ),
    sa.PrimaryKeyConstraint('modalidade_id', 'quadra_id')
    )
    op.drop_column('points', 'quadras')
    op.add_column('turmas', sa.Column('modalidade_id', sa.Integer(), nullable=False))
    op.add_column('turmas', sa.Column('quadra_id', sa.Integer(), nullable=False))
    op.add_column('turmas', sa.Column('duracao_minutos', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'turmas', 'quadras', ['quadra_id'], ['id'])
    op.create_foreign_key(None, 'turmas', 'modalidades', ['modalidade_id'], ['id'])
    op.drop_column('turmas', 'modalidade')
    op.drop_column('turmas', 'quadra')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('quadra', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('turmas', sa.Column('modalidade', mysql.VARCHAR(length=60), nullable=False))
    op.drop_constraint(None, 'turmas', type_='foreignkey')
    op.drop_constraint(None, 'turmas', type_='foreignkey')
    op.drop_column('turmas', 'duracao_minutos')
    op.drop_column('turmas', 'quadra_id')
    op.drop_column('turmas', 'modalidade_id')
    op.add_column('points', sa.Column('quadras', mysql.JSON(), nullable=False))
    op.drop_table('modalidade_quadras')
    op.drop_table('quadras')
    op.drop_table('modalidades')
    # ### end Alembic commands ###
