"""turma_periodo_vigencia

Revision ID: a9c4a4dc5441
Revises: 7d60f766a5ab
Create Date: 2026-08-20 01:56:15.573221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9c4a4dc5441'
down_revision: Union[str, None] = '7d60f766a5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('periodo_inicio', sa.Date(), nullable=False))
    op.add_column('turmas', sa.Column('periodo_fim', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turmas', 'periodo_fim')
    op.drop_column('turmas', 'periodo_inicio')
    # ### end Alembic commands ###
