"""credito_reposicao_data_aula

Revision ID: aaa0e05959d4
Revises: 27e2c21cf2f0
Create Date: 2026-08-20 00:38:09.131533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aaa0e05959d4'
down_revision: Union[str, None] = '27e2c21cf2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creditos_reposicao', sa.Column('data_aula', sa.Date(), nullable=False))
    op.add_column('creditos_reposicao', sa.Column('nova_matricula_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'creditos_reposicao', 'matriculas', ['nova_matricula_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creditos_reposicao', type_='foreignkey')
    op.drop_column('creditos_reposicao', 'nova_matricula_id')
    op.drop_column('creditos_reposicao', 'data_aula')
    # ### end Alembic commands ###
