"""planos_assinaturas_aulas

Revision ID: acdcf96e4aa1
Revises: a9c4a4dc5441
Create Date: 2026-08-20 02:36:28.616316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acdcf96e4aa1'
down_revision: Union[str, None] = 'a9c4a4dc5441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('frequencia_semanal', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('modalidade_id', sa.Integer(), nullable=False),
    sa.Column('frequencia_semanal_desejada', sa.Integer(), nullable=False),
    sa.Column('periodo_dia_desejado', sa.Enum('MANHA', 'TARDE', 'NOITE', name='periododia'), nullable=False),
    sa.Column('fonte_pagamento', sa.Enum('PIX', 'DINHEIRO', name='pagamentomeio'), nullable=False),
    sa.Column('status', sa.Enum('EM_ANALISE', 'ATIVA', 'RECUSADA', 'CANCELADA', name='matriculastatus'), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidades.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assinatura_turmas',
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('assinatura_id', 'turma_id')
    )
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', 'data', name='uq_aula_matricula_data')
    )
    op.add_column('matriculas', sa.Column('assinatura_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matriculas', 'assinaturas', ['assinatura_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matriculas', type_='foreignkey')
    op.drop_column('matriculas', 'assinatura_id')
    op.drop_table('aulas')
    op.drop_table('assinatura_turmas')
    op.drop_table('assinaturas')
    op.drop_table('planos')
    # ### end Alembic commands ###
