"""turma_periodo_fim_opcional

Revision ID: bb570b64f90a
Revises: acdcf96e4aa1
Create Date: 2026-08-20 13:58:30.341224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb570b64f90a'
down_revision: Union[str, None] = 'acdcf96e4aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turmas', 'periodo_fim',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turmas', 'periodo_fim',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
