"""fechamento_mensal

Revision ID: ecb8126b4bb7
Revises: aaa0e05959d4
Create Date: 2026-08-20 01:04:58.214444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ecb8126b4bb7'
down_revision: Union[str, None] = 'aaa0e05959d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('taxa_servico_unitaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_pagamentos', sa.Integer(), nullable=False),
    sa.Column('total_taxa_servico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repasses_fechamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechamento_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repasses_fechamento')
    op.drop_table('fechamentos')
    # ### end Alembic commands ###
